<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="ISO-8859-1">
    <title>Add Course</title>
    <!-- Include Tailwind CSS from a CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-700 text-gray-300 p-6">
    <div class="max-w-2xl mx-auto bg-gray-800 p-6 rounded-lg shadow-lg"> <!-- Darker form container -->
        <h1 class="text-2xl font-bold mb-4 text-gray-100">Add Course</h1>

        <!-- Form -->
        <form:form action="./addcourse" method="post" modelAttribute="bean" class="bg-gray-800 p-6 rounded-md shadow-md">
            <%-- Note: Course ID is usually generated by the database, so it's hidden --%>

            <div class="mb-4">
                <form:label path="name" class="block text-sm font-medium text-gray-400">Course Name</form:label>
                <form:input path="name" class="w-full bg-gray-700 border rounded-md text-gray-300 p-2" />
                <div class="text-red-400"><form:errors path="name" /></div>
            </div>

            <div class="mb-4">
                <form:label path="courseDescription" class="block text-sm font-medium text-gray-400">Course Description</form:label>
                <form:textarea path="courseDescription" class="w-full bg-gray-700 border rounded-md text-gray-300 p-2" rows="4" />
                <div class="text-red-400"><form:errors path="courseDescription" /></div>
            </div>

            <div class="mb-4">
                <form:label path="courseFees" class="block text-sm font-medium text-gray-400">Course Fees</form:label>
                <form:input type="number" path="courseFees" class="w-full bg-gray-700 border rounded-md text-gray-300 p-2" />
                <div class="text-red-400"><form:errors path="courseFees" /></div>
            </div>

            <div>
                <input type="submit" value="Add" class="bg-gray-500 hover:bg-gray-700 text-white px-4 py-2 rounded-md">
            </div>
        </form:form>
    </div>
</body>
<style>
    /* Hide scrollbar in WebKit-based browsers (Chrome, Safari) */
    ::-webkit-scrollbar {
        width: 0px; /* Width of the vertical scrollbar */
        height: 0px; /* Height of the horizontal scrollbar */
    }

    /* Hide scrollbar in Firefox */
    .container::-webkit-scrollbar {
        scrollbar-width: none;
    }
    
    /* Hide scrollbar in the container element */
    .container {
        overflow: hidden; /* Hide both horizontal and vertical scrollbars */
    }
</style>
</html>
